version: '3.4'

services:
  minha-webapi:
    image: minha-webapi:latest
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - ConnectionStrings__ServerConnection=Server=127.0.0.1,1433;Database=mydatabase;User Id=sa;Password=P@ssw0rd123!;Encrypt=False;
    depends_on:
      - sql_server
    ports:
      - "8001:80"
  
  sql_server:
    image: mcr.microsoft.com/mssql/server
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=P@ssw0rd123!
    ports:
      - "1433:1433"
